export type EnvVarDefinition = {
  key: string;
  category: string;
  required: boolean;
  description: string;
  missingWarning?: string;
};

export const ENV_DEFINITIONS: EnvVarDefinition[] = [
  {
    key: "AUTH_SECRET",
    category: "Core",
    required: true,
    description: "Session signing secret. Generate with openssl rand -base64 32.",
    missingWarning: "Authentication sessions cannot be securely signed, so users will be unable to log in reliably.",
  },
  {
    key: "DATABASE_URL",
    category: "Core",
    required: true,
    description: "Pooled Postgres connection string.",
    missingWarning: "The app cannot connect to Postgres, so most pages and API routes that read/write data will fail.",
  },
  {
    key: "DIRECT_URL",
    category: "Core",
    required: false,
    description: "Direct Postgres connection for Prisma migrations.",
  },
  {
    key: "CRON_SECRET",
    category: "Core",
    required: true,
    description: "Protects /api/cron/* endpoints.",
    missingWarning: "Scheduled cron endpoints cannot be securely protected, so cron jobs may fail or remain unsafe to expose.",
  },
  {
    key: "NEXTAUTH_URL",
    category: "Authentication",
    required: true,
    description: "Must match your exact production URL.",
    missingWarning: "OAuth callback URLs and auth redirects will break, preventing users from completing sign-in flows.",
  },
  {
    key: "NEXT_PUBLIC_APP_URL",
    category: "Authentication",
    required: true,
    description: "Used for building absolute links.",
    missingWarning: "The app cannot generate correct absolute URLs for links and callbacks, causing broken navigation in emails and auth flows.",
  },
  {
    key: "AUTH_GOOGLE_ID",
    category: "Authentication",
    required: true,
    description: "Google OAuth Client ID.",
    missingWarning: "Google OAuth cannot initialize, so Google sign-in will not be available.",
  },
  {
    key: "AUTH_GOOGLE_SECRET",
    category: "Authentication",
    required: true,
    description: "Google OAuth Client Secret.",
    missingWarning: "Google OAuth token exchange will fail, so users cannot authenticate with Google.",
  },
  {
    key: "ADMIN_EMAILS",
    category: "Admin Access",
    required: true,
    description: "Comma-separated admin emails. Requires redeploy on change.",
    missingWarning: "Admin allow-list checks cannot identify authorized admins, so admin access will be blocked.",
  },
  {
    key: "ADMIN_EMAIL_DOMAINS",
    category: "Admin Access",
    required: false,
    description: "Comma-separated admin email domains.",
  },
  {
    key: "AI_INGEST_ENABLED",
    category: "AI Ingest",
    required: true,
    description: "Set to 1 to enable AI extraction.",
    missingWarning: "AI ingest feature gating cannot be determined correctly, so extraction runs may be disabled or misconfigured.",
  },
  {
    key: "AI_INGEST_IMAGE_ENABLED",
    category: "AI Ingest",
    required: true,
    description: "Set to 1 to enable image import at approval time.",
    missingWarning: "Image import controls for ingest approvals cannot be evaluated, causing image import behavior to break.",
  },
  {
    key: "OPENAI_API_KEY",
    category: "AI Ingest",
    required: true,
    description: "Required when AI_INGEST_ENABLED=1.",
    missingWarning: "When AI ingest is enabled, model calls to OpenAI fail and extraction cannot run.",
  },
  {
    key: "BLOB_READ_WRITE_TOKEN",
    category: "AI Ingest",
    required: true,
    description: "Vercel Blob token for image storage. Auto-set when Blob is connected.",
    missingWarning: "Image uploads to Blob storage fail, so ingest image persistence and related workflows break.",
  },
  {
    key: "AI_VENUE_ENRICHMENT_ENABLED",
    category: "AI Pipeline",
    required: false,
    description: "Enables Phase 1 venue enrichment.",
  },
  {
    key: "AI_ARTIST_INGEST_ENABLED",
    category: "AI Pipeline",
    required: false,
    description: "Enables Phase 3 artist ingest.",
  },
  {
    key: "AI_ARTWORK_INGEST_ENABLED",
    category: "AI Pipeline",
    required: false,
    description: "Enables Phase 4 artwork ingest.",
  },
  {
    key: "GEMINI_API_KEY",
    category: "AI Pipeline",
    required: false,
    description: "Required for Gemini provider (Phase 2/3).",
  },
  {
    key: "ANTHROPIC_API_KEY",
    category: "AI Pipeline",
    required: false,
    description: "Required for Claude provider (Phase 2/4).",
  },
  {
    key: "GOOGLE_PSE_API_KEY",
    category: "AI Pipeline",
    required: false,
    description: "Required for discovery search (Phase 5).",
  },
  {
    key: "GOOGLE_PSE_CX",
    category: "AI Pipeline",
    required: false,
    description: "Programmable Search Engine ID for Phase 5.",
  },
  {
    key: "BRAVE_SEARCH_API_KEY",
    category: "AI Pipeline",
    required: false,
    description: "Fallback search provider for Phase 5.",
  },
  {
    key: "AI_INGEST_MAX_CANDIDATES_PER_VENUE_RUN",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 25.",
  },
  {
    key: "AI_INGEST_DUPLICATE_SIMILARITY_THRESHOLD",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 85.",
  },
  {
    key: "AI_INGEST_DUPLICATE_LOOKBACK_DAYS",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 30.",
  },
  {
    key: "AI_INGEST_CONFIDENCE_HIGH_MIN",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 75.",
  },
  {
    key: "AI_INGEST_CONFIDENCE_MEDIUM_MIN",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 45.",
  },
  {
    key: "AI_INGEST_CRON_MAX_VENUES",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 10.",
  },
  {
    key: "AI_INGEST_CRON_MAX_TOTAL_CREATED_CANDIDATES",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 100.",
  },
  {
    key: "AI_INGEST_CRON_TIME_BUDGET_MS",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 120000.",
  },
  {
    key: "AI_INGEST_CRON_CIRCUIT_BREAKER_WINDOW_HOURS",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 6.",
  },
  {
    key: "AI_INGEST_CRON_CIRCUIT_BREAKER_MIN_RUNS",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 5.",
  },
  {
    key: "AI_INGEST_CRON_CIRCUIT_BREAKER_FAIL_RATE",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 0.6.",
  },
  {
    key: "AI_INGEST_IMAGE_MAX_BYTES",
    category: "AI Ingest Tuning",
    required: false,
    description: "Default 5000000.",
  },
  {
    key: "UPSTASH_REDIS_REST_URL",
    category: "Rate Limiting",
    required: false,
    description: "Required for shared rate limiting across instances.",
  },
  {
    key: "UPSTASH_REDIS_REST_TOKEN",
    category: "Rate Limiting",
    required: false,
    description: "Pair with UPSTASH_REDIS_REST_URL.",
  },
  {
    key: "RESEND_WEBHOOK_SECRET",
    category: "Email",
    required: true,
    description: "Required for email delivery webhooks.",
    missingWarning: "Inbound email webhook verification fails, so delivery and event callbacks cannot be trusted or processed.",
  },
  {
    key: "UNSUBSCRIBE_TOKEN_SECRET",
    category: "Email",
    required: true,
    description: "Required for unsubscribe link signing.",
    missingWarning: "Unsubscribe links cannot be signed or validated, so recipients may be unable to unsubscribe safely.",
  },
  {
    key: "SENTRY_DSN",
    category: "Observability",
    required: false,
    description: "Enables error reporting via Sentry.",
  },
  {
    key: "SENTRY_TRACES_SAMPLE_RATE",
    category: "Observability",
    required: false,
    description: "Default 0.1.",
  },
  {
    key: "OPS_SECRET",
    category: "Observability",
    required: false,
    description: "Required for /api/ops/metrics bearer auth.",
  },
  {
    key: "ANALYTICS_SALT",
    category: "Observability",
    required: false,
    description: "Privacy-safe analytics deduplication salt.",
  },
  {
    key: "NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN",
    category: "Maps",
    required: false,
    description: "Enables /nearby map view.",
  },
  {
    key: "GEOCODER_PROVIDER",
    category: "Maps",
    required: false,
    description: "Defaults to mapbox. Set to google to use Google geocoding.",
  },
  {
    key: "GOOGLE_MAPS_API_KEY",
    category: "Maps",
    required: false,
    description: "Required only when GEOCODER_PROVIDER=google.",
  },
];
