ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VENUE_CLAIM_VERIFY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VENUE_CLAIM_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VENUE_CLAIM_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RSVP_CONFIRMED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'RSVP_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_CHANGE_NOTIFY';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EVENT_REMINDER_24H';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'NEW_USER_WELCOME';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BROADCAST';

ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'SKIPPED_UNSUBSCRIBED';

ALTER TABLE "NotificationOutbox"
  ADD COLUMN IF NOT EXISTS "attemptCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "nextRetryAt" TIMESTAMP(3);

ALTER TABLE "SiteSettings"
  ADD COLUMN IF NOT EXISTS "emailEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "emailFromAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "emailOutboxBatchSize" INTEGER;
