export interface SiteSettingsShape {
  ingestSystemPrompt: string | null;
  artworkExtractionSystemPrompt: string | null;
  artistBioSystemPrompt: string | null;
  ingestModel: string | null;
  ingestMaxOutputTokens: number | null;
  emailEnabled: boolean;
  emailFromAddress: string | null;
  resendApiKeySet: boolean;
  resendFromAddress: string | null;
  stripePublishableKey: string | null;
  stripeSecretKeySet: boolean;
  stripeWebhookSecretSet: boolean;
  platformFeePercent: number;
  emailOutboxBatchSize: number | null;
  analyticsSalt: string | null;
  openAiApiKeySet: boolean;
  geminiApiKeySet: boolean;
  anthropicApiKeySet: boolean;
  googlePseApiKeySet: boolean;
  braveSearchApiKeySet: boolean;
  googlePseCx: string | null;
  eventExtractionProvider: string | null;
  artworkExtractionProvider: string | null;
  artistLookupProvider: string | null;
  artistBioProvider: string | null;
  ingestEnabled: boolean;
  ingestImageEnabled: boolean;
  ingestMaxCandidatesPerVenueRun: number | null;
  ingestDuplicateSimilarityThreshold: number | null;
  ingestDuplicateLookbackDays: number | null;
  ingestConfidenceHighMin: number | null;
  ingestConfidenceMediumMin: number | null;
  venueGenerationModel: string | null;
  venueAutoPublish: boolean;
  regionAutoPublishVenues: boolean;
  regionAutoPublishEvents: boolean;
  regionAutoPublishArtists: boolean;
  regionAutoPublishArtworks: boolean;
  regionDiscoveryEnabled: boolean;
  regionMaxVenuesPerRun: number | null;
  enrichMatchedArtists: boolean;
  autoTagEnabled: boolean;
  autoTagProvider: string | null;
  autoTagModel: string | null;
  editorialNotifyTo: string | null;
  editorialNotificationsWebhookUrl: string | null;
  editorialNotificationsEmailEnabled: boolean;
  alertWebhookUrl: string | null;
  alertWebhookSecretSet: boolean;
  googleIndexingEnabled: boolean;
  googleServiceAccountJsonSet: boolean;
  resendConfigured?: boolean;
  envFallbacks?: {
    OPENAI_API_KEY: boolean;
    GEMINI_API_KEY: boolean;
    ANTHROPIC_API_KEY: boolean;
    GOOGLE_PSE_API_KEY: boolean;
    GOOGLE_PSE_CX: boolean;
    BRAVE_SEARCH_API_KEY: boolean;
    RESEND_API_KEY: boolean;
    STRIPE_SECRET_KEY: boolean;
    STRIPE_PUBLISHABLE_KEY: boolean;
    STRIPE_WEBHOOK_SECRET: boolean;
    GOOGLE_SERVICE_ACCOUNT_JSON: boolean;
  };
}
